[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
charity_contract = "6cCF1c3Q3Rx92ECJYQj3QZMG9rfgydjfUd6jkFD8VTEF"

[registry]
url = "https://api.apr.dev"
## url = "http://localhost:3000"

[provider]
cluster = "Devnet"
##cluster = "http://127.0.0.1:8898"  # Match the RPC URL of the test validator
wallet = "~/.solana/.config/localwallet.json"

## Specify WebSocket URL explicitly
[websocket]
## url = "ws://127.0.0.1:8898"
url = "wss://api.devnet.solana.com"  

## [scripts]
## test = "yarn run ts-mocha \"-p\" ./tsconfig.json -t 1000000 tests/**/*.ts"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

