[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
charity_contract = "9kqZ3ma4VY6Kmj7vgb1qPiLDoxb46zM5eEm1rsQZTG9L"

## [registry]
## url = "https://api.apr.dev"

[registry]
url = "http://localhost:3000"

## [provider]
## cluster = "Devnet"
## wallet = "~/.solana/.config/localwallet.json"

[provider]
cluster = "http://127.0.0.1:8898"  # Match the RPC URL of the test validator
wallet = "~/.solana/.config/localwallet.json"

# Specify WebSocket URL explicitly
[websocket]
url = "ws://127.0.0.1:8898"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
